### ISSUE TITLE
在 Xcode 10.3 版本安装这个框架会报错

### ISSUE THREAD

**Issue by Atlan8** [lixiang1994/AttributedString#10]
![WechatIMG13](https://user-images.githubusercontent.com/32053512/88501394-f1e1bd00-cffd-11ea-8d43-6c6e3f88d458.jpeg)
![WechatIMG14](https://user-images.githubusercontent.com/32053512/88501404-f908cb00-cffd-11ea-89ec-0218e83c4727.jpeg)
![WechatIMG15](https://user-images.githubusercontent.com/32053512/88501408-fdcd7f00-cffd-11ea-9368-25391522fbb4.jpeg)

大佬，我pod安装了 AttributedString ，然后在运行项目就报错了，xcode 的版本是 10.3 的，模拟器的iOS版本是 12.4 的

**Comment by lixiang1994** [comment]
emmm.. swift版本太低了, 怎么不用xcode11??  都一年了... 不适配13吗?

**Comment by Atlan8** [comment]
这就很尴尬，电脑是公司的，因为有老的项目要维护，所以没升级……

**Comment by lixiang1994** [comment]
那14出了 岂不是更维护不动了

**Comment by Atlan8** [comment]
哈哈哈，反正是老大叫我不要升级的，俺也搞不懂

**Comment by lixiang1994** [comment]
那新系统岂不是没法适配咯, 总不是个长久之计

**Comment by Atlan8** [comment]
我回头跟老大说一下吧，不过这台Mac是15款的，我也不清楚公司的安排，哈哈哈

**Comment by lixiang1994** [comment]
嗯嗯 iOS本来和别的系统就不一样 更新太快了, 现在iOS11和iOS12的用户就很少了
