### ISSUE TITLE
请教一个同一行设置图片和文字，怎么做能让他们居中对齐呢

### ISSUE THREAD

**Issue by simpleLiYu** [lixiang1994/AttributedString#11]
![image](https://user-images.githubusercontent.com/20043672/88749414-d1446f00-d185-11ea-8acc-3ce1ae7c532a.png)

**Comment by lixiang1994** [comment]
我不清楚你现在的代码怎么写的, 我举几个例子:

```
// 设置推荐的大小(一般为行高) 位置居中
\(.image(#imageLiteral(resourceName: "swift-icon"), .proposed(.center)))

// 设置图片原始大小 (宽度不会超过整行长度) 位置居中
\(.image(#imageLiteral(resourceName: "swift-icon"), .original(.center)))
```

**Comment by simpleLiYu** [comment]
谢谢指导，设置了proposed这个之后是不是就不能设置customsize了，这个设置是只能有一个选项吗？

**Comment by lixiang1994** [comment]
对的, 都是设置尺寸.

**Comment by simpleLiYu** [comment]
嗯嗯，我试了一下，设置了customsize之后图片不能居中，设置.proposed(.center)图片大小就不对，这两个能不能同时设置？

**Comment by lixiang1994** [comment]
custom 可以居中呀  
```
 \(.image(#imageLiteral(resourceName: "swift-icon"), .custom(.center, size: .init(width: 50, height: 50))))
```

**Comment by simpleLiYu** [comment]
草率了草率了，我再看下。感谢开源，感谢指导，谢谢。另外大佬的LEEalert可准备Swift一下，一直用你的LEEAlert很方便。再次感谢。

**Comment by lixiang1994** [comment]
感谢支持 Alert的不知道啊 库再多点我可能管不过来了就.

**Comment by simpleLiYu** [comment]
好的，辛苦。奥利给

**Comment by China-jxsg-YanYuanJie** [comment]
.custom(.center, size: .init(width: 50, height: 50))))
我用这个一样会有偏差 并没有居中  不知道为什么

**Comment by lixiang1994** [comment]
图片居中取决于所在的文本font

**Comment by China-jxsg-YanYuanJie** [comment]
他的规则是如何计算的呢？比如16大小的字体，10高度的图片，我需要居中如何计算
