### ISSUE TITLE
检查样式add这个方法没有

### ISSUE THREAD

**Issue by liyunlong1512** [lixiang1994/AttributedString#14]
var string: AttributedString = """
            我的名字叫李响，我的手机号码是18611401994，我的电子邮件地址是18611401994@163.com，现在是2020/06/28 20:30。我的GitHub主页是https://github.com/lixiang1994。欢迎来Star! \("点击联系我", .action(clicked))
            """
            string.add(attributes: [.foreground(#colorLiteral(red: 0.9529411793, green: 0.6862745285, blue: 0.1333333403, alpha: 1)), .font(.systemFont(ofSize: 20, weight: .medium))], checkings: [.phoneNumber])
            string.add(attributes: [.foreground(#colorLiteral(red: 0.1764705926, green: 0.4980392158, blue: 0.7568627596, alpha: 1)), .font(.systemFont(ofSize: 20, weight: .medium))], checkings: [.link])
            string.add(attributes: [.foreground(#colorLiteral(red: 0.1764705926, green: 0.01176470611, blue: 0.5607843399, alpha: 1)), .font(.systemFont(ofSize: 20, weight: .medium))], checkings: [.date])
            string.add(attributes: [.font(.systemFont(ofSize: 20, weight: .medium))], checkings: [.action])
            container.label.attributed.text = string

**Comment by lixiang1994** [comment]
??? 没明白

**Comment by liyunlong1512** [comment]
上面那段代码是我拷贝的你dome里面的，但是我pod下来的库里面，是没有add(attributes: [.foreground(#colorLiteral()), .font()], checkings: )这个方法的，这个是需要自己去处理吗

**Comment by lixiang1994** [comment]
咦 你的版本是多少? 是不是没更新??

**Comment by liyunlong1512** [comment]
解决了我的版本问题，更新到1.6.6就好了，谢谢
