### ISSUE TITLE
里面的图片是GIF的支持动画吗

### ISSUE THREAD

**Issue by simpleLiYu** [lixiang1994/AttributedString#15]

**Comment by lixiang1994** [comment]
UITextView支持添加自定义视图 你可以加一个UIImageView

**Comment by simpleLiYu** [comment]
我尝试用UITextView加一个UIImageView，但是我设置的size并没有用

**Comment by lixiang1994** [comment]
发一下你的代码我看看

**Comment by simpleLiYu** [comment]
![iShot2020-08-26下午02 01 08](https://user-images.githubusercontent.com/20043672/91266824-9e04f800-e7a4-11ea-89f7-0e3fb5dd23b0.png)
![iShot2020-08-26下午02 00 10](https://user-images.githubusercontent.com/20043672/91266839-a5c49c80-e7a4-11ea-9c2f-b1a77ad733f5.png)
![iShot2020-08-26下午01 59 55](https://user-images.githubusercontent.com/20043672/91266854-aa895080-e7a4-11ea-9073-ae5f3be50807.png)

**Comment by simpleLiYu** [comment]
DiamondImageView是继承UIImageView的子类

**Comment by simpleLiYu** [comment]
好像图片和文字放在同一行设置大小就有问题

**Comment by lixiang1994** [comment]
咦, 我这边测试好像没发现什么问题
<img width="981" alt="image" src="https://user-images.githubusercontent.com/13112992/91268667-51bbb700-e7a8-11ea-809a-8c7e2db5afdc.png">
<img width="240" alt="image" src="https://user-images.githubusercontent.com/13112992/91268754-7152df80-e7a8-11ea-9a08-0f91c42a07f7.png">

**Comment by simpleLiYu** [comment]
你这个不是宽高设置的40吗，图示是一个长方形的。初始化时设置的宽高没有生效吧

**Comment by lixiang1994** [comment]
我不是用的`custom(size:)`嘛, 会以`custom(size:)`为主, 你也可以不设置 不设置默认为原始大小 也就是view的frame

**Comment by simpleLiYu** [comment]
你下面用的custom(size:)是吧，不好意思没细看。。。你尝试一下把字体设置大点，然后图片的高度比文字的高度小，就不正确了

**Comment by lixiang1994** [comment]
一共三种样式类型, proposed是建议的大小 相当于当前行高 和旁边文字一样大, original是原始大小 很好理解, custom是自定义大小

**Comment by simpleLiYu** [comment]
当文字高度比图片高度高，这时候设置custom样式就没有效果了，那这样是不是就没办法设置文字大，后面跟的图片小些了

**Comment by lixiang1994** [comment]
咦 那可能是BUG 我看看啊

**Comment by simpleLiYu** [comment]
![image](https://user-images.githubusercontent.com/20043672/91272873-03f67d00-e7af-11ea-8cfb-2c45192a9fa7.png)
就是这样的，文字字体设置的大之后设置图片的高度就无效了，会和文字一样高

**Comment by lixiang1994** [comment]
嗯嗯 我已经复现了, 这两天应该可以解决 有点小麻烦

**Comment by simpleLiYu** [comment]
大佬辛苦，爱你哟❤️

**Comment by lixiang1994** [comment]
@simpleLiYu  1.6.7

**Comment by simpleLiYu** [comment]
欧卡
