### ISSUE TITLE
自定义视图控件后，无法设置段落样式吗？

### ISSUE THREAD

**Issue by liyunlong1512** [lixiang1994/AttributedString#17]
textView.attributed.text = .init(
            """
            \(.view(customLabel, .original(.center)))\(" 两市涨跌不一，医疗器械集体走强两市涨跌不一，医疗器械集体走强", .font(.systemFont(ofSize: 17, weight: .medium)), .paragraph(.lineSpacing(5)))
            \("美国三大股指涨跌不一，道指下1.39%，纳指上涨0.53%，标普500下跌0.56%...", .paragraph(.lineSpacing(5)))
            """,
            .font(.systemFont(ofSize: 15))
        )
设置自定义视图控件之后，段落样式无法生效，如果不添加自定义视图控件则能正常显示

**Comment by lixiang1994** [comment]
其实不是加了自定义视图的问题, 是富文本段落的特性, 你在段落前面加任何内容段落样式都会无效, 我给你个例子 你可以这样写:

将你加的视图和段落内容放到一起 而不是直接加到段落内容前面.

```
textView.attributed.text = .init(
"""
 \(wrap: "\(.view(customLabel, .original(.center)))  两市涨跌不一，医疗器械集体走强两市涨跌不一，医疗器械集体走强", .font(.systemFont(ofSize: 17, weight: .medium)), .paragraph(.lineSpacing(10)))
 \("美国三大股指涨跌不一，道指下1.39%，纳指上涨0.53%，标普500下跌0.56%...", .paragraph(.lineSpacing(10)))
 """,
.font(.systemFont(ofSize: 15))
 )
```

<img width="1043" alt="image" src="https://user-images.githubusercontent.com/13112992/92235587-81746880-eee6-11ea-9898-82de3552f152.png">


<img width="392" alt="image" src="https://user-images.githubusercontent.com/13112992/92235378-280c3980-eee6-11ea-99d0-e4b77da1f3ec.png">

**Comment by lixiang1994** [comment]
或者 将段落设置放到外层 也可以.

<img width="1002" alt="image" src="https://user-images.githubusercontent.com/13112992/92296398-c213c680-ef66-11ea-8414-c1234b47ce1d.png">

**Comment by liyunlong1512** [comment]
let customLabel = UILabel()

//customLabel.frame = CGRect(x: 0, y: 8.0, width: 60, height: 10)

 customLabel.text = " 午盘概览 "

 customLabel.textColor = .white

 customLabel.font = .systemFont(ofSize: 10, weight: .regular)

 customLabel.backgroundColor = .red

 customLabel.textAlignment = .center

 customLabel.sizeToFit()

 customLabel.layer.cornerRadius = 3

 customLabel.layer.masksToBounds = true




textView.attributed.text = .init(

"""

\(wrap: "\(.view(customLabel, .original(.center)))  两市涨跌不一，医疗器械集体走强两市涨跌不一，医疗器械集体走强", .font(.systemFont(ofSize: 17, weight: .medium)), .paragraph(.minimumLineHeight(26)))

\("美国三大股指涨跌不一，道指下1.39%，纳指上涨0.53%，标普500下跌0.56%...",            .paragraph(.minimumLineHeight(22)))

""",

.font(.systemFont(ofSize: 15))

)



多谢老哥回复我的问题，段落样式解决了，但是这个tag标签的位置需要通过什么方法去设置，我有设置original(.offset)但是也不能设置标签的位置及大小，谢谢

**Comment by lixiang1994** [comment]
`. original(.center)` 的意思是 原始大小 位置居中 你的无效应该是因为你没有设置frame 
你也可以试试`.custom(.center, CGSize)`

**Comment by liyunlong1512** [comment]
let redView = UIImageView(frame: .init(x: 0, y: 0, width: 10, height: 10))

        redView.image = UIImage.init(named: "swift-icon")

        

        textView.attributed.text = .init(

            """

            \(wrap: "\(.view(redView, .custom(.center, size: .init(width: 10, height: 10))))  两市涨跌不一，医疗器械集体走强两市涨跌不一，医疗器械集体走强", .font(.systemFont(ofSize: 17, weight: .medium)), .paragraph(.lineSpacing(4.5)))

            \("美国三大股指涨跌不一，道指下1.39%，纳指上涨0.53%，标普500下跌0.56%...", .paragraph(.lineSpacing(3.5)))

            """,

            .font(.systemFont(ofSize: 15))

        )




我这里已经设置了view的大小，但是这里的图片高度被拉伸了,多了一个行高的高度










在 2020-09-07 10:28:56，"LEE" <notifications@github.com> 写道：

. original(.center) 的意思是 原始大小 位置居中 你的无效应该是因为你没有设置frame
你也可以试试.custom(.center, CGSize)

**Comment by lixiang1994** [comment]
@liyunlong1512 没太明白, 你可以提供代码运行的截图吗?

**Comment by liyunlong1512** [comment]
在 2020-09-07 13:37:14，"LEE" <notifications@github.com> 写道：

@liyunlong1512 没太明白, 你可以提供代码运行的截图吗?

**Comment by TheDukeFamily** [comment]
我也碰到了类似这个问题，在网络请求后，刷新视图的时候，发现附件图片宽度比实际宽度要小
///插入换行符
                    var attr = AttributedString.init("")
        ///key：图片的位置 value 图片的名称 [key, value]
        for item in children {
            let element = item as? GDataXMLElement
            guard element?.name() == "p" else { continue }
            if let xmlText = element?.stringValue(), String.isNotNullOrEmpty(xmlText) {/// 表情或文字
                /// 声明数组 [["0","文字"],["1","表情"]]
                let xmlTextList = xmlText.expressionStringWithArray()
                for xmlTextListItem in xmlTextList {
                    if let path = pp_BundleMainPath(xmlTextListItem, "gif"), xmlTextListItem.hasPrefix("[") , xmlTextListItem.hasSuffix("]") {
                        // 插入对应的gif图片
                        let customImageView = UIImageView.aspectFitImageView()
                        // 更改自定义视图的大小 (x y 无效)
                        customImageView.frame = .init(x: 0, y: 0, width: 80.scale, height: 80.scale)
                        customImageView.loadLocalImage(path)
                        attr += AttributedString.init("\(.view(customImageView, .original(.origin)))")
                    } else {
                        // 插入文本内容
                        attr += AttributedString.init("\(xmlTextListItem, .foreground(pp_color(.C222222)), .font(.systemFont(ofSize: 18.scale)), .paragraph(.lineSpacing(8.scale)))")
                    }
                }
            }else{///图片或文字
                if let imgs = element?.elements(forName: "img"), imgs.count > 0 {
                    ///插入换行符
                    attr += AttributedString.init("\("\n", .font(.systemFont(ofSize: 12.scale)), .paragraph(.lineSpacing(0.scale)))")
                        
                    /// 获取图片附件并插入
                    let image = imgs[0] as? GDataXMLElement
                    let imageUrl = image?.attribute(forName: "src")?.stringValue() ?? ""
                    var imageWidth:CGFloat = image?.attribute(forName: "width")?.stringValue()?.f ?? 0
                    var imageHeight:CGFloat = image?.attribute(forName: "height")?.stringValue()?.f ?? 0
                    let imageSizeRate = imageHeight / imageWidth
                    if imageWidth > pp_screen_width - 30.scale {
                        imageWidth = pp_screen_width - 30.scale
                        imageHeight = imageWidth * imageSizeRate
                    }
                    let customImageView = UIImageView.aspectFillImageView()
                    customImageView.frame = .init(x: 0, y: 0, width: imageWidth, height: imageHeight)
                    customImageView.backgroundColor = .red
                    // 更改自定义视图的大小 (x y 无效)
                    customImageView.loadImage(imageUrl, placeholder: .rectangle)
                    customImageView.makeCornerRadius(5.scale)
                    attr += AttributedString.init("\(.view(customImageView, .original(.origin)))")
                }else {
                    // 插入换行符
                    attr += AttributedString.init("\("\n", .font(.systemFont(ofSize: 12.scale)), .paragraph(.lineSpacing(0.scale)))")
                }
            }
        }
        self.attributed.text = attr

**Comment by lixiang1994** [comment]
@TheDukeFamily 
是这段代码无效吗?
```
                ......
                customImageView.frame = .init(x: 0, y: 0, width: imageWidth, height: imageHeight)
                customImageView.backgroundColor = .red
                // 更改自定义视图的大小 (x y 无效)
                customImageView.loadImage(imageUrl, placeholder: .rectangle)
                customImageView.makeCornerRadius(5.scale)
                attr += AttributedString.init("\(.view(customImageView, .original(.origin)))")
```

**Comment by TheDukeFamily** [comment]
@lixiang1994 是的，textView是加在cell上面，然后现在是这样一个问题，在网络请求之后，如果添加了图片，会出现错位的情况，样式如下图
![截屏2020-10-31 上午10 46 41](https://user-images.githubusercontent.com/14728051/97769474-64ff5000-1b66-11eb-8324-d43797b2c510.png)
然后我又在cell的layoutsubviews里面添加了TextView.attributed.layout()，现在好像没发现问题，这个问题是偶先的，可以说下造成这种问题的原因吗

**Comment by lixiang1994** [comment]
布局没刷新好导致的, 你试试在赋值文本后面加上呢?
例如这样:
```
 textView.attributed.text = attr
 textView.attributed.layout()
```

**Comment by lixiang1994** [comment]
如果你是用约束布局 试试先调用layoutIfNeed() 保证textview已经为最终大小后, 再设置文本
