### ISSUE TITLE
UITableViewCell中，tap手势与cell的点击事件冲突。

### ISSUE THREAD

**Issue by lx176163** [lixiang1994/AttributedString#18]
UITableViewCell中，label的tap手势与cell的点击事件冲突。

导致tap手势，需要长按才能识别。

长按之后，tap事件响应了，cell的点击事件也同时响应了。

**Comment by chaoshenglu** [comment]
原来是因为delaysContentTouches

昨晚被这玩意儿折磨了一晚上😭 💔

**Comment by lx176163** [comment]
原来是因为delaysContentTouches

昨晚被这玩意儿折磨了一晚上😭 💔
