### ISSUE TITLE
富文本编辑插值问题

### ISSUE THREAD

**Issue by wentaoStudy** [lixiang1994/AttributedString#2]
如果我想用来做富文本编辑器，插入图片的时候具体该怎么定位插入图片的位置呢？

**Comment by lixiang1994** [comment]
这只是对NSAttributedString的一种封装, 要看NSAttributedString本身支持什么.

**Comment by wentaoStudy** [comment]
嗯，我使用其他方式对NSAttributedString进项添加Attachment操作了

**Comment by lixiang1994** [comment]
你如果只是要Attachment添加 我是支持的呀

**Comment by lixiang1994** [comment]
NSAttributedString自身支持的特性 我都有提供

**Comment by lixiang1994** [comment]
AttachmentViewController

**Comment by wentaoStudy** [comment]
你这里目前只支持在句子的尾部添加，没有直接在句子中间添加attachment的方法
我用的是NSMutableAttributedString 的insert方法在固定位置插入

**Comment by lixiang1994** [comment]
.... 你看我Demo了吗?

**Comment by wentaoStudy** [comment]
可编辑情况下，你的demo是支持attachment，但是只支持在句尾插入啊，README里面的+=看了

**Comment by lixiang1994** [comment]
啊 明白了 你的是编辑器 是动态添加的

**Comment by wentaoStudy** [comment]
对，是这个意思
