### ISSUE TITLE
点击事件识别不灵敏

### ISSUE THREAD

**Issue by qingshanbugai** [lixiang1994/AttributedString#21]
let d: AttributedString = .init("《隐私协议》", .font(.font12), .foreground(.red_F84417), .action(.click, {[weak self] in
                
            }))
响应不及时，按一秒以上才能响应

**Comment by lixiang1994** [comment]
基于Touch实现 请检查视图层级是否在UIScrollView上导致的?

**Comment by qingshanbugai** [comment]
> 基于Touch实现 请检查视图层级是否在UIScrollView上导致的?

视图层级中不存在UIscrollView及其子类

**Comment by qingshanbugai** [comment]
label太靠底部就会识别不灵敏，比如单行label，字体14，距底部16，就很难点击

**Comment by lixiang1994** [comment]
label太靠底部 这句话怎么理解? 安全区外?  点击范围是由实际显示的文字范围决定的

**Comment by qingshanbugai** [comment]
> label太靠底部 这句话怎么理解? 安全区外? 点击范围是由实际显示的文字范围决定的

安全区内，比如6s的底部，你的demo里的label，放到最下面，只放一行，也是点击不灵敏的

**Comment by ganweiming** [comment]
@lixiang1994 您好.我也发现这个问题. Action.Trigger.click 类型时如果快速点击或者轻点触发不了点击事件. 重按或者停留时间稍久一点即可, 基于.Touch实现是否有可能是使用Touch Up Outside. 换成Touch Up Inside是否可以解决此问题.Thanks so much

**Comment by lixiang1994** [comment]
@ganweiming 是重写touchesBegan..., 快速点击触发不了 可能是由于你UI层级中有拦截Touch的东西导致Touch延迟了, 比如UIScrollView

**Comment by ganweiming** [comment]
@lixiang1994 是的.我使用了UIScrollView嵌套. 但是我禁用了滚动后仍然存在此问题

**Comment by lixiang1994** [comment]
不是禁用滚动, 有个`delaysContentTouches`的属性你可以了解一下

**Comment by r9ronaldozhang** [comment]
我也有上诉问题，cell中使用，click几乎无效，按的时间长一点儿，才会有响应，希望能优化一下，或者给一个解决方案，毕竟cell太常用了

**Comment by lixiang1994** [comment]
2.2.0 已解决 无需再设置delaysContentTouches 🎉 🎉 🎉
