### ISSUE TITLE
numberOfLines 为0时候点击无效

### ISSUE THREAD

**Issue by MuRanJiangXia** [lixiang1994/AttributedString#27]
多行显示label  点击事件无效，切不能多行显示了

**Comment by MuRanJiangXia** [comment]
给 label的 image增加的点击事件，但是无效

**Comment by MuRanJiangXia** [comment]
nameLabel.attributed.text = "\(nameString) \(.image(icon, bounds: CGRect(x: 0, y: -4, width: 20, height: 20)), trigger: .click, action: editName)"

我设置的是 click 但是要长按一会才走回调事件

**Comment by lixiang1994** [comment]
你的label是在某UIScrollView内吗?

**Comment by MuRanJiangXia** [comment]
是的呢，在collectionview 上的

**Comment by lixiang1994** [comment]
有个delaysContentTouches的属性你可以设置一下 目前是基于touchesBegan做的 会受到UIScrollView事件传递影响

**Comment by MuRanJiangXia** [comment]
恩恩 谢谢啦

**Comment by MuRanJiangXia** [comment]
你好，还有个问题，label多行显示有时候图片显示不出来呢
