### ISSUE TITLE
不能像按钮那样点击触发点击事件

### ISSUE THREAD

**Issue by yangguanghei** [lixiang1994/AttributedString#28]
得稍微长按才能触发点击事件，且文字高梁、还有下划线

**Comment by lixiang1994** [comment]
有个delaysContentTouches的属性你可以设置一下 目前是基于touchesBegan做的 会受到UIScrollView事件传递影响

默认的高亮样式是带下划线 你可以设置成你想要的

**Comment by yangguanghei** [comment]
> 有个delaysContentTouches的属性你可以设置一下 目前是基于touchesBegan做的 会受到UIScrollView事件传递影响
> 
> 默认的高亮样式是带下划线 你可以设置成你想要的

按照你说的设置了delaysContentTouches属性，可以了。但没找到怎么去掉高亮和下划线，

**Comment by lixiang1994** [comment]
<img width="826" alt="image" src="https://user-images.githubusercontent.com/13112992/118768936-29359900-b8b2-11eb-9279-75a7ac7d4f95.png">

**Comment by lixiang1994** [comment]
2.2.0 已解决 无需再设置delaysContentTouches 🎉 🎉 🎉
