### ISSUE TITLE
与Swift5.5冲突

### ISSUE THREAD

**Issue by tylerlamp** [lixiang1994/AttributedString#31]

**Comment by lixiang1994** [comment]
哎 还是苹果爸爸强势, 我想办法解决一下

**Comment by tylerlamp** [comment]
给我们一个教训，不要把系统命名直接去掉"NS"后，作为自己的命名。
说不定哪一天，苹果想起来要改了。
期待你的消息。祝你好运。

**Comment by lixiang1994** [comment]
https://github.com/lixiang1994/AttributedString/releases/tag/2.0.0 已发布

**Comment by tylerlamp** [comment]
现在Cocoapods 能拉到最新版吗

**Comment by lixiang1994** [comment]
可以
