### ISSUE TITLE
下划线 patternDash 怎么不起作用？

### ISSUE THREAD

**Issue by AlleniCode** [lixiang1994/AttributedString#35]

**Comment by lixiang1994** [comment]
代码发一下, 是正常写不起作用 还是用这个插值设置不起作用?

**Comment by AlleniCode** [comment]
```
let text: AttributedString = "\("AAA", .underline(.patternDot, color: .black))"
label.attributed.text = text
```

@lixiang1994 还有个问题，这个下划线和文字间的距离怎么设置啊？Thanks♪(･ω･)ﾉ

**Comment by lixiang1994** [comment]
大概是这样子 
```
\("underline: double color: .red", .underline([.patternDot, .thick], color: .black), .kern(10))
```

**Comment by lixiang1994** [comment]
@AlleniCode 你少了个参数

**Comment by AlleniCode** [comment]
@lixiang1994 我试了一下，下划线有了，但是那个间距不对，我想要的效果是”文字“与”下划线“之间的距离，不是文字之间的😅

还有就是下划线的粗细可以调整吗？有点粗了🤔

<img width="129" alt="QQ20210903-134908@2x" src="https://user-images.githubusercontent.com/8855341/131956818-1290d5df-88e2-4965-8afd-da15bc5a0695.png">

**Comment by lixiang1994** [comment]
下划线的间距不能自定义, 就那么几种style, 本质就是设置NSAttributedString.Key.underlineStyle, NSUnderlineStyle

**Comment by lixiang1994** [comment]
NSAttributedString支持的都能支持, 在这之外我实现了点击长按和自定义视图等扩展, 其他的都不是基于UILabel和UITextView可以做到的了

**Comment by AlleniCode** [comment]
好的，谢谢👍🏻
