### ISSUE TITLE
考虑增加点击和长按手势同时支持

### ISSUE THREAD

**Issue by huanglins** [lixiang1994/AttributedString#37]
这两个手势本身不会冲突，是否考虑可同时添加。

**Comment by lixiang1994** [comment]
好的, 我近期抽时间解决一下这个问题

**Comment by ETmanwenhan** [comment]
> 好的, 我近期抽时间解决一下这个问题

非常感谢大神！

**Comment by lixiang1994** [comment]
@ETmanwenhan @huanglins  3.0.0版本已支持

**Comment by ETmanwenhan** [comment]
> @ETmanwenhan @huanglins 3.0.0版本已支持

感谢大神，来得太及时了🙏

**Comment by ETmanwenhan** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，谢谢你联系我。我会尽快给您回复。

**Comment by ETmanwenhan** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，谢谢你联系我。我会尽快给您回复。
