### ISSUE TITLE
多语言怎么支持呢

### ISSUE THREAD

**Issue by burning-git** [lixiang1994/AttributedString#38]
目前本文有点击事件，因为内容是拼接的，导致多语言识别起来困难。

**Comment by lixiang1994** [comment]
具体场景是?

**Comment by lixiang1994** [comment]
我理解是可以给不同的点击事件闭包 并不需要区分具体文本

**Comment by burning-git** [comment]
已经决绝了。拼接 NSMutableAttributedString

例如 ：
文本： 请您务必认真阅读《用户协议》和《隐私政策》中的各项条款.

`      let user_protocol = ASAttributedString("《用户协议》", .action({[weak self] in
            self?.userProtocolClicked()
        }), .foreground(.textThemeColor), .font(.pingFang(14, fontWeight: .Regular))).value
        
        let privacy_protocol = ASAttributedString("《隐私政策》", .action({[weak self] in
            self?.privacyPolicyClicked()
        }), .foreground(.textThemeColor), .font(.pingFang(14, fontWeight: .Regular))).value
   `
请您务必认真阅读\(user_protocol)和\(privacy_protocol)中的各项条款
“请您务必认真阅读\(user_protocol)和\(privacy_protocol)中的各项条款” 这块需要多语言支持
