### ISSUE TITLE
请教下大兄弟计算富文本高度的问题

### ISSUE THREAD

**Issue by qiaqiaxian** [lixiang1994/AttributedString#4]
看了demo中的方法
但是发现有自定义字体，或者\n情况比较多的话
高度计算会有一些偏差
请问下还有更准确的方法吗？

**Comment by lixiang1994** [comment]
有没有例子? 你把你计算有问题的字符串发我 我试试

**Comment by lixiang1994** [comment]
这个方法我用了挺久了, 而且我demo的文本有图有换行 也挺复杂了, 你用的是UILabel还是UITextView?

**Comment by qiaqiaxian** [comment]
用的UITextView
这里高度计算会多出一段
<img width="435" alt="WX20200608-114216@2x" src="https://user-images.githubusercontent.com/21219815/83990718-2b426880-a97d-11ea-91b2-605a51cf974b.png">
这里又是准确的
<img width="432" alt="WX20200608-114226@2x" src="https://user-images.githubusercontent.com/21219815/83990743-3f866580-a97d-11ea-8e5e-4411fdf97a6e.png">

附上文件，谢谢


[test.json.zip](https://github.com/lixiang1994/AttributedString/files/4743744/test.json.zip)

**Comment by lixiang1994** [comment]
你把json里面的字符串复制到我Demo中试试, 我试了一下 没有计算不对, 你发一下你`UITextView`设置的代码.

**Comment by qiaqiaxian** [comment]
> 你把json里面的字符串复制到我Demo中试试, 我试了一下 没有计算不对, 你发一下你`UITextView`设置的代码.

好的，我先试试

**Comment by qiaqiaxian** [comment]
在你的demo中测试正常
计算高度代码中
`width: UIScreen.main.bounds.width - 20,`   
我设置的-30，因为我左右两边间距都是15
`return list[indexPath.row].height + 20` 
之前没有+20
改成和demo一样的就正常了
想问下这两个数字是需要固定的吗？

**Comment by lixiang1994** [comment]
```
textView.textContainer.lineFragmentPadding = 0
textView.textContainerInset = .zero
```
设置了吗?

**Comment by qiaqiaxian** [comment]
> ```
> textView.textContainer.lineFragmentPadding = 0
> textView.textContainerInset = .zero
> ```
> 
> 设置了吗?

之前设置了，不准确，把那两个数字改成和你一样的就正常了

**Comment by lixiang1994** [comment]
是已经好了吗?

**Comment by lixiang1994** [comment]
boundingRect只是计算富文本所需高度, 但是UITextView自身有内边距 所以需要计算进去才能得到最终的高度

**Comment by qiaqiaxian** [comment]
> 是已经好了吗?

是的，改成和你一样的正常了，但是根据我的UI边距-30就不对，不知道什么情况

**Comment by lixiang1994** [comment]
我Demo也是这样吗?

**Comment by qiaqiaxian** [comment]
> 我Demo也是这样吗?

对，我就把文本粘贴过去了，没改其他地方显示正常

但是如果这个
`self.height = content.value.boundingRect(
                with: .init(
                    width: UIScreen.main.bounds.width - 20,
                    height: .greatestFiniteMagnitude
                ),
                options: [
                    .usesLineFragmentOrigin,
                    .usesFontLeading
                ],
                context: nil
            ).integral.size.height`
-20 改成-30也会计算多出一段空白

**Comment by lixiang1994** [comment]
emmm... 我改成-30了 一样正常啊..
<img width="576" alt="image" src="https://user-images.githubusercontent.com/13112992/83993765-fcc98b00-a986-11ea-8a2f-32acaee0c627.png">

![image](https://user-images.githubusercontent.com/13112992/83993736-e4f20700-a986-11ea-8819-e6d46ae6f20c.png)

**Comment by qiaqiaxian** [comment]
-30
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-06-08 at 12 56 52](https://user-images.githubusercontent.com/21219815/83993984-a741ae00-a987-11ea-9389-ef030609ba24.png)
-20
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-06-08 at 12 57 12](https://user-images.githubusercontent.com/21219815/83993997-b1fc4300-a987-11ea-9fd0-3765bf016bc7.png)
`.font(UIFont(name: "HelveticaNeue", size: 14.0)!), .color(#colorLiteral(red: 0.6000000238, green: 0.6000000238, blue: 0.6000000238, alpha: 1)),.paragraph(.lineSpacing(8)))`

你试试下我这个参数

**Comment by lixiang1994** [comment]
确实 似乎和字体有关

**Comment by qiaqiaxian** [comment]
> 确实 似乎和字体有关

破案了，用system字体确实没问题

**Comment by lixiang1994** [comment]
是啊 蛋疼的问题, 而且我发现啊, 你在后面拼任意一个字符 就正常了.
就是这样:
```
"\("", xxx())任意字符"
```

**Comment by lixiang1994** [comment]
似乎结尾如果是个systemFont的任意字符就可以

**Comment by qiaqiaxian** [comment]
确实 - -
nsattributedstring不像nsstring那样
boundingRect可以设置attributes

**Comment by lixiang1994** [comment]
结案了结案了, 哈哈

**Comment by qiaqiaxian** [comment]
okok，如果有什么新进展，给大兄弟说声

**Comment by lixiang1994** [comment]
👌, 总结一下, 如果用`boundingRect`这种方式计算高度, 存在非systemFont时, 可以在后面拼一个systemFont的空格解决计算不准确的问题. 目前测试来看 只要保证结尾的最后一个字符是systemFont就可以计算正确.

**Comment by fero2004** [comment]
boundingRect 这个方法好像只能用systomfont来计算,其他字体计算会不准确

**Comment by lixiang1994** [comment]
@fero2004 你可以参考https://www.jianshu.com/p/dde8966df46e 这个. 虽然有点小问题 但是能用, swift的我这边还没开源 测试中

**Comment by tangzzz-fan** [comment]
> 

这个做法太 tricky 了, 有没有更新更好的做法?
