### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by liyuemin7** [lixiang1994/AttributedString#40]
Xcode 13 
let attr : ASAttributedString = "\("lee", .action(clicked))"

error:

Cannot infer contextual base in reference to member 'action'
Generic parameter 'T' could not be inferred

**Comment by lixiang1994** [comment]
let attr : ASAttributedString = "\("lee", .action(clicked))"

**Comment by lixiang1994** [comment]
let attr : ASAttributedString = "\("lee", .action(clicked))"
