### ISSUE TITLE
重构Action没有兼容低版本吗？我代码之前都可以跳转，升级后点击事件没了

### ISSUE THREAD

**Issue by zhangxiongwen** [lixiang1994/AttributedString#41]
昨天刚上线，今天就被发现线上重大bug，回退到2.2.2就可以跳转

**Comment by zhangxiongwen** [comment]
代码如下
string.add(attributes: [.action([.foreground(.init(hexString: "#4099FF"))], {
                print("click")
            })], range: item.range)

**Comment by lixiang1994** [comment]
抱歉, 是一个BUG, 稍后我会发布新版本修复 (。・＿・。)ﾉI’m sorry~

**Comment by zhangxiongwen** [comment]
> 抱歉, 是一个BUG, 稍后我会发布新版本修复 (。・＿・。)ﾉI’m sorry~

辛苦了

**Comment by lixiang1994** [comment]
已更新 3.0.1

**Comment by zhangxiongwen** [comment]
> 已更新 3.0.1

👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻
