### ISSUE TITLE
控制器的某个Label属性使用了.action 造成该控制器没有调用deinit

### ISSUE THREAD

**Issue by HZRZCW** [lixiang1994/AttributedString#44]
如题！！！！！！

**Comment by lixiang1994** [comment]
代码截图, 闭包内是否加了[weak self] ?

**Comment by HZRZCW** [comment]
> 代码截图, 闭包内是否加了[weak self] ?

闭包内没有任何代码也一样会。

**Comment by lixiang1994** [comment]
??? 我测试了Demo中的页面 都是可以正常deinit的, 可以提供尽可能全的代码截图吗? 方便分析

**Comment by HZRZCW** [comment]
> ??? 我测试了Demo中的页面 都是可以正常deinit的, 可以提供尽可能全的代码截图吗? 方便分析

我再测试一下

**Comment by lixiang1994** [comment]
注意 action回调闭包即使你传入的是一个function, 只要使用了外部变量就会产生引用

**Comment by lixiang1994** [comment]
Demo中ActionViewController 里 使用的就是function形式, 如果在方法内要访问self, 如下:
```
        weak var `self` = self
        func clicked(_ result: ASAttributedString.Action.Result) {
            self?.label.backgroundColor = .brown
        }
```

**Comment by lixiang1994** [comment]
验证了一下, 确实如此, Swift语法的定义, 可以曲线救国的方法只有在方法内嵌套一个子方法调用外部方法了.
```
        weak var `self` = self
        func clicked(_ result: ASAttributedString.Action.Result) {
            self?.clicked(result)
        }
```

**Comment by HZRZCW** [comment]
> 验证了一下, 确实如此, Swift语法的定义, 可以曲线救国的方法只有在方法内嵌套一个子方法调用外部方法了.
> 
> ```
>         weak var `self` = self
>         func clicked(_ result: ASAttributedString.Action.Result) {
>             self?.clicked(result)
>         }
> ```

能用就行，不过可以提醒下其他人

**Comment by ETmanwenhan** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，谢谢你联系我。我会尽快给您回复。

**Comment by ZClee128** [comment]
作者快点解决一下吧

**Comment by lixiang1994** [comment]
> 重新打开吧，有别的问题 ![image](https://private-user-images.githubusercontent.com/18162711/324797919-819ea7f7-8b7a-4de0-a212-35b4f9362243.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5NjQ0NjksIm5iZiI6MTcxNDk2NDE2OSwicGF0aCI6Ii8xODE2MjcxMS8zMjQ3OTc5MTktODE5ZWE3ZjctOGI3YS00ZGUwLWEyMTItMzViNGY5MzYyMjQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDAyNTYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwNTMxM2UxZmMxMDgxYzkyNWI1OWVkZjYyYWEwYzdiMTgwYWZmOGUxYWEwOGViZGM4YzkwOGI0MDY0YTgwMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.92ar6s8zoUH3Bew3HfEdLtrZmBmj4dluTuOdrbD1Dw8) zhe zhon这种写法也是会导致不走deinit

是的, 上面有人提到了 

![](https://user-images.githubusercontent.com/12219811/162139054-d183a042-69ec-4b48-b03d-7a95e7465d29.png)

**Comment by ZClee128** [comment]
> > 重新打开吧，还有其他问题![图像](https://private-user-images.githubusercontent.com/18162711/324797919-819ea7f7-8b7a-4de0-a212-35b4f9362243.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5NjQ0NjksIm5iZiI6MTcxNDk2NDE2OSwicGF0aCI6Ii8xODE2MjcxMS8zMjQ3OTc5MTktODE5ZWE3ZjctOGI3YS00ZGUwLWEyMTItMzViNGY5MzYyMjQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDAyNTYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwNTMxM2UxZmMxMDgxYzkyNWI1OWVkZjYyYWEwYzdiMTgwYWZmOGUxYWEwOGViZGM4YzkwOGI0MDY0YTgwMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.92ar6s8zoUH3Bew3HfEdLtrZmBmj4dluTuOdrbD1Dw8)zhon这种写法也会导致走不了deinit
> 
> 是的，上面有人提到过
> 
> ![](https://user-images.githubusercontent.com/12219811/162139054-d183a042-69ec-4b48-b03d-7a95e7465d29.png)

我看到很长时间没有解决，希望大佬可以抓紧时间修复一下

**Comment by lixiang1994** [comment]
> > > 重新打开吧，还有其他问题![图像](https://private-user-images.githubusercontent.com/18162711/324797919-819ea7f7-8b7a-4de0-a212-35b4f9362243.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5NjQ0NjksIm5iZiI6MTcxNDk2NDE2OSwicGF0aCI6Ii8xODE2MjcxMS8zMjQ3OTc5MTktODE5ZWE3ZjctOGI3YS00ZGUwLWEyMTItMzViNGY5MzYyMjQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDAyNTYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwNTMxM2UxZmMxMDgxYzkyNWI1OWVkZjYyYWEwYzdiMTgwYWZmOGUxYWEwOGViZGM4YzkwOGI0MDY0YTgwMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.92ar6s8zoUH3Bew3HfEdLtrZmBmj4dluTuOdrbD1Dw8)zhon这种写法也会导致走不了deinit
> > 
> > 
> > 是的，上面有人提到过
> > ![](https://user-images.githubusercontent.com/12219811/162139054-d183a042-69ec-4b48-b03d-7a95e7465d29.png)
> 
> 我看到很长时间没有解决，希望大佬可以抓紧时间修复一下

这受限于Swift特性, 我无法解决, 只能建议绕开这种用法

**Comment by ZClee128** [comment]
> > > > 重新打开吧，还有其他问题![图像](https://private-user-images.githubusercontent.com/18162711/324797919-819ea7f7-8b7a-4de0-a212-35b4f9362243.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5NjQ0NjksIm5iZiI6MTcxNDk2NDE2OSwicGF0aCI6Ii8xODE2MjcxMS8zMjQ3OTc5MTktODE5ZWE3ZjctOGI3YS00ZGUwLWEyMTItMzViNGY5MzYyMjQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDAyNTYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwNTMxM2UxZmMxMDgxYzkyNWI1OWVkZjYyYWEwYzdiMTgwYWZmOGUxYWEwOGViZGM4YzkwOGI0MDY0YTgwMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.92ar6s8zoUH3Bew3HfEdLtrZmBmj4dluTuOdrbD1Dw8)zhon这种写法也会导致走不了deinit
> > > 
> > > 
> > > 是的，上面有人提到过
> > > ![](https://user-images.githubusercontent.com/12219811/162139054-d183a042-69ec-4b48-b03d-7a95e7465d29.png)
> > 
> > 
> > 我看到很长时间没有解决，希望大佬可以抓紧时间修复一下
> 
> 这受限于Swift特性, 我无法解决, 只能建议绕开这种用法

好吧😂

**Comment by dagundejuzi** [comment]
> weak var `self` = self

还有一种写法，把子控件的引用设为weak。
```
 weak var hasAttrV: UIView?
……
let v = getAttrView
superView.addSubview(v)
hasAttrV = v
```
一直没搞明白，这个子View到底是怎么持有到控制器的，action指向控制器的函数或者闭包，就能持有了？用 [weak self] 都不行？

**Comment by ETmanwenhan** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，谢谢你联系我。我会尽快给您回复。
