### ISSUE TITLE
ASAttributedString如何通过range截取部分富文本？

### ISSUE THREAD

**Issue by zhangxiongwen** [lixiang1994/AttributedString#46]
NSAttributedString 有这个方法 attributedString .attributedSubstring(from: range)
ASAttributedString应该如何通过range获取部分富文本呢？

**Comment by lixiang1994** [comment]
ASAttributedString有value属性 可以取到NSAttributedString

**Comment by zhangxiongwen** [comment]
比如说 let str =  ASAttributedString()
contentLab.attributed.text = str
我现在要截取str的一部分显示，如果我用ASAttributedString有value属性获取到的值是NSAttributedString类型，但是我要给contentLab.attributed.text 赋值, 这个是ASAttributedString类型的，要怎么写呢？

**Comment by lixiang1994** [comment]
contentLab.attributed.text = .init(str.value.attributedSubstring(from: range))

**Comment by lixiang1994** [comment]
如果可以 我还是建议分开创建ASAttributedString, 没必要对ASAttributedString进行截取

**Comment by lixiang1994** [comment]
是什么场景需要你做截取?

**Comment by zhangxiongwen** [comment]
我要在末尾加上展开折叠，然后在计算出range后截取 ，在末尾追加展开折叠

**Comment by lixiang1994** [comment]
哈哈 好吧 那确实需要截取

**Comment by zhangxiongwen** [comment]
> contentLab.attributed.text = .init(str.value.attributedSubstring(from: range))

这样写会不会对已经添加的属性 比如点击事件或者其他的属性有影响呢？

**Comment by zhangxiongwen** [comment]
好 感谢大佬
