### ISSUE TITLE
AttributedString.swift文件中别名的问题

### ISSUE THREAD

**Issue by XuanYuLanFeng** [lixiang1994/AttributedString#49]
在AttributedString.swift中第14行至第24行代码中
#if os(macOS)
import AppKit
public typealias Image = NSImage
public typealias Color = NSColor
public typealias Font = NSFont
#else
import UIKit
public typealias Image = UIImage
public typealias Color = UIColor
public typealias Font = UIFont
#endif
上述代码中别名Image会与SwiftUI中的Image(uiImage:(UIImage(systemName: ""))!)起冲突，可以测试一下，如有此问题，可以修改别名，或者添加前缀如public typealias LXImage = NSImage

**Comment by lixiang1994** [comment]
已更名为ASImage.. 3.3.3
