### ISSUE TITLE
TextView 图片偏移显示不全

### ISSUE THREAD

**Issue by huanglins** [lixiang1994/AttributedString#50]
给 textView 设置 contentInset 后，比如 `UIEdgeInsets(top: 16, left: 20, bottom: 16, right: 20)` ，图片会比预期的更靠右，如果是一个带圆角的图片就能很明显的看得出来，右边的圆角没有显示完全。

**Comment by lixiang1994** [comment]
?

**Comment by huanglins** [comment]
看了下是需要设置 `textView.textContainerInset = .zero`，如果不设置的话就会有这个问题，如果能兼容一下这种情况也不错。
