### ISSUE TITLE
Is it possible to make the backlight when the button is pressed?

### ISSUE THREAD

**Issue by ivanvorobei** [lixiang1994/AttributedString#6]
Maybe simple alpha 0.7 when button pressed. If it implemented already, I can create PR with updating readme. 
I think it very important show highlight state for button

**Comment by lixiang1994** [comment]
I have plans to add highlights, but the way I extend them limits the richness of the styles. I need more time to solve these problems.




| |
LEE
邮箱：18611401994@163.com
|

Signature is customized by Netease Mail Master

On 06/13/2020 00:51, Ivan Vorobei wrote:

Maybe simple alpha 0.7 when button pressed. If it implemented already, I can create PR with updating readme.
I think it very important show highlight state for button

**Comment by lixiang1994** [comment]
I don't want to use custom subclasses or views




| |
LEE
邮箱：18611401994@163.com
|

Signature is customized by Netease Mail Master

On 06/13/2020 01:01, LEE wrote:
I have plans to add highlights, but the way I extend them limits the richness of the styles. I need more time to solve these problems.




| |
LEE
邮箱：18611401994@163.com
|

Signature is customized by Netease Mail Master

On 06/13/2020 00:51, Ivan Vorobei wrote:

Maybe simple alpha 0.7 when button pressed. If it implemented already, I can create PR with updating readme.
I think it very important show highlight state for button

**Comment by lixiang1994** [comment]
Supported in version 1.4.0. 🎉

**Comment by ivanvorobei** [comment]
Many thanks, it really work! 
Very fast) 

One last think, maybe available do dimmed style for clickable action? 
I recorded video, you can [see it](https://cdn.ivanvorobei.by/temp/dimmedexample.mov). 

Also this code for my buttons

<img width="811" alt="Screenshot 2020-06-20 at 11 25 52" src="https://user-images.githubusercontent.com/10995774/85197352-210f5b00-b2e9-11ea-82b6-871523fe59a8.png">

Not sure available use it in text views. But support dimmed for clickable very natively. I close this issue, and if you can do dimmed mode - I will open new.

**Comment by lixiang1994** [comment]
I already have some ideas, maybe two weeks.

**Comment by ivanvorobei** [comment]
If need, I can create other issue

**Comment by lixiang1994** [comment]
It's ok

**Comment by lixiang1994** [comment]
Supported in version 1.5.0. 🎉

e.g.

<img width="1421" alt="image" src="https://user-images.githubusercontent.com/13112992/86507001-331fec00-be07-11ea-8797-4884c7fae539.png">

**Comment by lixiang1994** [comment]
https://github.com/lixiang1994/AttributedString/releases/tag/1.5.0

**Comment by ivanvorobei** [comment]
Many thanks! it work!
