### ISSUE TITLE
能否更新下 CocoaPods 还是1.2.0的

### ISSUE THREAD

**Issue by q8533557** [lixiang1994/AttributedString#7]

**Comment by lixiang1994** [comment]
你pod本地仓库内更新吧，试试pod setup




| |
LEE
邮箱：18611401994@163.com
|

Signature is customized by Netease Mail Master

在2020年06月15日 18:08，q8533557 写道：

**Comment by q8533557** [comment]
指定了版本也不行

**Comment by lixiang1994** [comment]
试一下 pod setup




| |
LEE
邮箱：18611401994@163.com
|

Signature is customized by Netease Mail Master

在2020年06月15日 18:14，q8533557 写道：

指定了版本也不行

**Comment by q8533557** [comment]
pod setup 然后 pod install --> Installing AttributedString (1.2.0) 还是出现了 这个

**Comment by lixiang1994** [comment]
用pod update 命令更新




| |
LEE
邮箱：18611401994@163.com
|

Signature is customized by Netease Mail Master

在2020年06月16日 08:26，q8533557 写道：

pod setup 然后 pod install --> Installing AttributedString (1.2.0) 还是出现了 这个

**Comment by lixiang1994** [comment]
你也可以尝试用vpn或者4g网络




| |
LEE
邮箱：18611401994@163.com
|

Signature is customized by Netease Mail Master

在2020年06月16日 08:29，LEE 写道：
用pod update 命令更新




| |
LEE
邮箱：18611401994@163.com
|

Signature is customized by Netease Mail Master

在2020年06月16日 08:26，q8533557 写道：

pod setup 然后 pod install --> Installing AttributedString (1.2.0) 还是出现了 这个

**Comment by q8533557** [comment]
网络问题....

**Comment by lixiang1994** [comment]
哈哈，我天朝自有国情在此




| |
LEE
邮箱：18611401994@163.com
|

Signature is customized by Netease Mail Master

在2020年06月16日 09:06，q8533557 写道：

网络问题....

**Comment by lixiang1994** [comment]
关闭了哈




在2020年06月16日 09:08，LEE 写道：
哈哈，我天朝自有国情在此




| |
LEE
邮箱：18611401994@163.com
|

Signature is customized by Netease Mail Master

在2020年06月16日 09:06，q8533557 写道：

网络问题....

**Comment by q8533557** [comment]
好------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;LEE&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年6月16日(星期二) 上午10:07
收件人:&nbsp;&quot;lixiang1994/AttributedString&quot;<AttributedString@noreply.github.com&gt;;
抄送:&nbsp;&quot;q8533557&quot;<729342839@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [lixiang1994/AttributedString] 能否更新下 CocoaPods 还是1.2.0的 (#7)
