### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by Plotac** [lixiang1994/AttributedString#71]
带有action的AttributedString好像都会有内存泄漏问题。例如demo中的ActionViewController，CheckingViewController，大佬看看能不能优化下。
![8b70a91f-4945-4876-9774-ed10e5749932](https://github.com/user-attachments/assets/dbc7eb5c-832d-49b2-8088-4a0c896f9286)

**Comment by lixiang1994** [comment]
好的, 已发布3.4.2, 你试试
