### ISSUE TITLE
大神，图片在tableview里面点击无响应啊

### ISSUE THREAD

**Issue by q8533557** [lixiang1994/AttributedString#8]

**Comment by lixiang1994** [comment]
纳尼？ 可以提供一些代码截图吗？

**Comment by q8533557** [comment]
在你demo主页的tabelview加点击事件



---原始邮件---
发件人: "LEE"<notifications@github.com&gt;
发送时间: 2020年6月16日(周二) 下午3:49
收件人: "lixiang1994/AttributedString"<AttributedString@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"q8533557"<729342839@qq.com&gt;;
主题: Re: [lixiang1994/AttributedString] 大神，图片在tableview里面点击无响应啊 (#8)




 
纳尼？ 可以提供一些代码截图吗？

**Comment by lixiang1994** [comment]
好的，我试试

**Comment by lixiang1994** [comment]
啊 是这样的, 必须通过这种设置方式点击才会生效, Demo列表这块代码有点老了.
<img width="576" alt="image" src="https://user-images.githubusercontent.com/13112992/84752306-2b331000-aff0-11ea-8a79-df5f00cdc1cf.png">

**Comment by q8533557** [comment]
求大神源码



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "LEE"<notifications@github.com&gt;; 
发送时间: 2020年6月16日(星期二) 下午4:41
收件人: "lixiang1994/AttributedString"<AttributedString@noreply.github.com&gt;; 
抄送: "729342839"<729342839@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [lixiang1994/AttributedString] 大神，图片在tableview里面点击无响应啊 (#8)





 
啊 是这样的, 必须通过这种设置方式点击才会生效, Demo列表这块代码有点老了.

**Comment by lixiang1994** [comment]
稍后我更新一下Demo代码

**Comment by q8533557** [comment]
好的感谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "LEE"<notifications@github.com&gt;; 
发送时间: 2020年6月16日(星期二) 下午4:44
收件人: "lixiang1994/AttributedString"<AttributedString@noreply.github.com&gt;; 
抄送: "729342839"<729342839@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [lixiang1994/AttributedString] 大神，图片在tableview里面点击无响应啊 (#8)





 
稍后我更新一下Demo代码

**Comment by lixiang1994** [comment]
拉一下吧 你再试试

**Comment by simpleLiYu** [comment]
你好，是先写好AttributedString  @lixiang1994 在通过attributed.text=这个AttributedString来生效吗。我这样写并没有点击事件是咋回事
![image](https://user-images.githubusercontent.com/20043672/90102036-5dec5100-dd72-11ea-8275-f5cc7903dfb9.png)

**Comment by lixiang1994** [comment]
userWechat是个label吗? 可以看一下你label的配置吗?

**Comment by simpleLiYu** [comment]
是一个label，需要配置什么吗？我仅仅是初始化了一个label

**Comment by lixiang1994** [comment]
> 是一个label，需要配置什么吗？我仅仅是初始化了一个label

了解了 我测试一下看看

**Comment by simpleLiYu** [comment]
好的好的

**Comment by lixiang1994** [comment]
@simpleLiYu 
我模拟了你的富文本 没有发现问题 
能提供更具体的说明吗?, 或者你可以查看一下UI层级是否有其他View遮挡住了Label, 内部的点击手势是在attributed.text设置时添加的.

<img width="1245" alt="image" src="https://user-images.githubusercontent.com/13112992/90130058-5e014680-dd9c-11ea-90e7-7f872870636b.png">

**Comment by lixiang1994** [comment]
@simpleLiYu 可以检查是否添加在了ScrollView上 ScrollView是否设置了`delaysContentTouches`属性, 这些情况都对点击有一定影响

**Comment by simpleLiYu** [comment]
我放在在tableview的cell和collectionview的cell里面

**Comment by lixiang1994** [comment]
你可以试试是不是点时间长一点 他就有反应了, 我猜测是delaysContentTouches属性影响的touch

**Comment by lixiang1994** [comment]
参考这个 https://www.jianshu.com/p/2b171f6153ad 理解一下

**Comment by simpleLiYu** [comment]
@lixiang1994 还真的是，我看看你这个简书的谢谢
