### ISSUE TITLE
Invalid line spacing for last line with button

### ISSUE THREAD

**Issue by ivanvorobei** [lixiang1994/AttributedString#9]
Attached example:

<img src="https://user-images.githubusercontent.com/10995774/86479919-b3861480-bd55-11ea-8d5b-2e76ddb35d59.png" width="250">

Code for init:

```swift
let text = AttributedString(NSAttributedString(string: text), .font(textFont), .color(descriptionLabel.textColor))
        let button = AttributedString(NSAttributedString(string: button), .font(buttonFont), .color(buttonColor), .action([.color(buttonColor.withAlphaComponent(0.5))], action))
        descriptionLabel.attributed.text = text + " " + button
```

Code for layout

```swift
titleLabel.frame.origin = .zero
titleLabel.frame.set(width: frame.width)
titleLabel.sizeToFit()
        
descriptionLabel.frame = CGRect.init(x: 0, y: titleLabel.frame.bottomY + 4, width: frame.width, height: 0)
descriptionLabel.sizeToFit()
```

Number of lines set to zero.

**Comment by lixiang1994** [comment]
I tried to run your code, but found no problems.
I don't see the line spacing setting, can I send more detailed information?

**Comment by lixiang1994** [comment]
My mock code:

<img width="1022" alt="image" src="https://user-images.githubusercontent.com/13112992/86503449-c691f680-bde0-11ea-9ea0-145d929a00f1.png">

<img width="456" alt="image" src="https://user-images.githubusercontent.com/13112992/86503452-d3aee580-bde0-11ea-8de3-d73e56dcbb2f.png">

**Comment by lixiang1994** [comment]
I found that when there are two different font sizes in a row, it will look like in the screenshot.

This is a problem of NSAttributedString, but I know how to make him achieve the desired effect.

Can be solved by setting the line height:
```
label.attributed.text = .init(text + " " + button, .paragraph(.maximumLineHeight(30), .minimumLineHeight(30)))
```

e.g.

<img width="1269" alt="image" src="https://user-images.githubusercontent.com/13112992/86504336-c9451980-bde9-11ea-8b73-f4a11a3c9b51.png">

<img width="444" alt="image" src="https://user-images.githubusercontent.com/13112992/86504325-b6324980-bde9-11ea-8a7f-a975ff31bee3.png">

**Comment by lixiang1994** [comment]
The root cause is the difference between line spacing and line height.

**Comment by ivanvorobei** [comment]
I try set -2, and it no do anything for me. If positive - doing

**Comment by lixiang1994** [comment]
Is the line height invalid?

**Comment by ivanvorobei** [comment]
I set only `maximum` & `minimum`, no do any additional. It need?

**Comment by lixiang1994** [comment]
```
let text = AttributedString(string: text, .font(textFont), .color(descriptionLabel.textColor))
        let button = AttributedString(string: button, .font(buttonFont), .color(buttonColor), .action([.color(buttonColor.withAlphaComponent(0.5))], action))
descriptionLabel.attributed.text = .init(text + " " + button, .paragraph(.maximumLineHeight(30), .minimumLineHeight(30)))
```
After running this code, what is the result?

**Comment by ivanvorobei** [comment]
With `30` spacing more. But I try set `-2` or even zero. Result this: 

<img width="439" alt="Screenshot 2020-07-07 at 13 52 40" src="https://user-images.githubusercontent.com/10995774/86770294-2561a500-c059-11ea-8415-a45fc2eef783.png">

**Comment by lixiang1994** [comment]
God, can you extract more complete code for me, I need to debug and analyze.

**Comment by lixiang1994** [comment]
Before that, I need to confirm whether the system font is used?

**Comment by ivanvorobei** [comment]
Sorry, I simple use your code as you send. 
This that I use 

```swift
let textFont = UIFont.preferredFont(forTextStyle: .footnote)
        let buttonFont = UIFont.preferredFont(forTextStyle: .footnote, weight: .medium)
        
        let textAttributed = AttributedString(NSAttributedString(string: text + text), .font(textFont), .foreground(descriptionLabel.textColor))
        let buttonAttributed = AttributedString(NSAttributedString(string: button), .font(buttonFont), .foreground(buttonColor), .action([.foreground(buttonColor.withAlphaComponent(0.5))], action))
        descriptionLabel.attributed.text = .init(textAttributed + " " + buttonAttributed, .paragraph(.maximumLineHeight(-2), .minimumLineHeight(-2)))
```

**Comment by lixiang1994** [comment]
`UIFont.preferredFont(forTextStyle: .footnote, weight: .medium) ` ???  Is it an extension?

**Comment by lixiang1994** [comment]
my code:

<img width="1168" alt="image" src="https://user-images.githubusercontent.com/13112992/86773017-a6d02c00-c087-11ea-95a4-d118c0c8b3d0.png">
<img width="415" alt="image" src="https://user-images.githubusercontent.com/13112992/86773050-b0f22a80-c087-11ea-8a95-2e14c1419d68.png">

**Comment by lixiang1994** [comment]
Line height must be greater than 0 to take effect

**Comment by ivanvorobei** [comment]
@lixiang1994 you full right. I set zero and it not work. When I set `textFont.lineHeight` it start work
Thanks for your time and big help!

**Comment by lixiang1994** [comment]
Line spacing and line height are different.

**Comment by lixiang1994** [comment]
My pleasure

**Comment by ivanvorobei** [comment]
Sorry, catch strange behaviour.

Code

```swift
let textFont = UIFont.preferredFont(forTextStyle: .footnote)
let buttonFont = UIFont.preferredFont(forTextStyle: .footnote, weight: .medium).rounded()
let buttonColor = SPInterface.tintColor
        
let text = "you full right. I set zero and it not work. When I set textFont.lineHeight it start work. Thanks for your time and big help!"
let button = "Action"
let textAttributed = AttributedString(NSAttributedString(string: text), .font(textFont), .foreground(descriptionLabel.textColor))
        let buttonAttributed = AttributedString(NSAttributedString(string: button), .font(buttonFont), .foreground(buttonColor), .action([.foreground(buttonColor.withAlphaComponent(0.5))], {
            print("call")
        }))
descriptionLabel.numberOfLines = 0
descriptionLabel.attributed.text = .init(textAttributed + " " + buttonAttributed, .paragraph(.maximumLineHeight(textFont.lineHeight), .minimumLineHeight(textFont.lineHeight)))
        
scrollView.addSubview(descriptionLabel)
descriptionLabel.frame = CGRect.init(x: 20, y: 20, width: 200, height: 0)
descriptionLabel.sizeToFit()
```

It basic code, only with line height. 
But if text small (you can set one work and button and text in 1 line) - all work, if many lines (like example which I attach), button not clickable

**Comment by lixiang1994** [comment]
Try it. 
```
scrollView.delaysContentTouches = fasle
```

**Comment by ivanvorobei** [comment]
`descriptionLabel` placed not on scroll view

**Comment by lixiang1994** [comment]
???
<img width="982" alt="image" src="https://user-images.githubusercontent.com/13112992/86893386-20255880-c134-11ea-8a5b-149b7f479b9d.png">

**Comment by ivanvorobei** [comment]
Yes, in example. I try remove it and place to view. Similar bug

**Comment by lixiang1994** [comment]
My code
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/13112992/86913204-deef7180-c150-11ea-91d7-e09a11d4532b.png">

Can you check the touch response?
For example `Parent view` `isUserInteractionEnabled`

**Comment by ivanvorobei** [comment]
Even adding to empty project, also not work. I did example, you can check?
[attributed-not-call.zip](https://github.com/lixiang1994/AttributedString/files/4891016/attributed-not-call.zip)

**Comment by lixiang1994** [comment]
Thanks.
I have fixed it. 🎉
Because I use font leading, but some fonts are incomplete.
Please update to version [1.5.2](https://github.com/lixiang1994/AttributedString/releases/tag/1.5.2).

**Comment by ivanvorobei** [comment]
It work now! 
Thanks!
